# Generated by Django 2.1.7 on 2019-05-07 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('item_num', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique ID for this particular item across whole library')),
                ('notes', models.CharField(max_length=500, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Deployed', 'Deployed')], default='Available', max_length=25)),
                ('description', models.TextField(choices=[('Building Materials', 'Building Materials'), ('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Clothing', 'Clothing'), ('Outdoor', 'Outdoor'), ('Pet Supplies', 'Pet Supplies'), ('Recreational', 'Recreational'), ('Vehicle', 'Vehicle')], default='Outdoor', max_length=25)),
                ('sector', models.CharField(choices=[('North-West', 'NW'), ('North-Center', 'NC'), ('North-East', 'NE'), ('Central-West', 'CW'), ('Central-Center', 'CC'), ('Central-East', 'CE'), ('South-West', 'SW'), ('South-Center', 'SC'), ('South-East', 'SE'), ('Off Site', 'OS')], default='NW', max_length=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('borrower', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrjMgr',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emp_num', models.IntegerField(blank=True, db_index=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='joined')),
                ('role', models.CharField(choices=[('Project Manager I', 'Project Manager I'), ('Project Manager II', 'Project Manager II'), ('Project Manager III', 'Project Manager III'), ('Project Planner', 'Project Planner'), ('Project Coordinator', 'Project Coordinator'), ('Supervisor', 'Supervisor')], default='Project Manager I', max_length=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical prj mgr',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('prj_num', models.IntegerField(blank=True, db_index=True)),
                ('summary', models.TextField(blank=True, help_text='Enter project description', max_length=1000, null=True)),
                ('date_created', models.DateField(blank=True, editable=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('prj_status', models.TextField(choices=[('Behind Schedule', 'Behind Schedule'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Planning', 'Planning')], default='Planning', max_length=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_num', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular item across whole library', primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Deployed', 'Deployed')], default='Available', max_length=25)),
                ('description', models.TextField(choices=[('Building Materials', 'Building Materials'), ('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Clothing', 'Clothing'), ('Outdoor', 'Outdoor'), ('Pet Supplies', 'Pet Supplies'), ('Recreational', 'Recreational'), ('Vehicle', 'Vehicle')], default='Outdoor', max_length=25)),
                ('sector', models.CharField(choices=[('North-West', 'NW'), ('North-Center', 'NC'), ('North-East', 'NE'), ('Central-West', 'CW'), ('Central-Center', 'CC'), ('Central-East', 'CE'), ('South-West', 'SW'), ('South-Center', 'SC'), ('South-East', 'SE'), ('Off Site', 'OS')], default='NW', max_length=25)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrjMgr',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emp_num', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='joined')),
                ('role', models.CharField(choices=[('Project Manager I', 'Project Manager I'), ('Project Manager II', 'Project Manager II'), ('Project Manager III', 'Project Manager III'), ('Project Planner', 'Project Planner'), ('Project Coordinator', 'Project Coordinator'), ('Supervisor', 'Supervisor')], default='Project Manager I', max_length=25)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_num', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, help_text='Enter project description', max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('prj_status', models.TextField(choices=[('Behind Schedule', 'Behind Schedule'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Planning', 'Planning')], default='Planning', max_length=12)),
                ('prj_mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.PrjMgr')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='prj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.Project'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='prj_mgr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resreq.PrjMgr'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='prj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resreq.Project'),
        ),
    ]
