# Generated by Django 2.1.7 on 2019-05-01 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_num', models.UUIDField(default=uuid.uuid4,
                                              help_text='Unique ID for this particular item across whole library',
                                              primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=500)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('status',
                 models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('D', 'Deployed')], default='A',
                                  max_length=1)),
                ('description', models.CharField(
                    choices=[('BLDG', 'Building Materials'), ('LVRM', 'Living Room'), ('KITC', 'Kitchen'),
                             ('BDRM', 'Bedroom'), ('BATH', 'Bathroom'), ('CLTH', 'Clothing'), ('OUTD', 'Outdoor'),
                             ('PETS', 'Pet Supplies'), ('RECR', 'Recreational'), ('VEHI', 'Vehicle')], default='BLDG',
                    max_length=4)),
                ('sector', models.CharField(
                    choices=[('NW', 'North-West'), ('NC', 'North-Center'), ('NE', 'North-East'), ('CW', 'Central-West'),
                             ('CC', 'Central-Center'), ('CE', 'Central-East'), ('SW', 'South-West'),
                             ('SC', 'South-Center'), ('SE', 'South-East'), ('OS', 'Off site')], default='NW',
                    max_length=2)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrjMgr',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emp_num', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='joined')),
                ('title', models.CharField(choices=[('PM1', 'Project Manager I'), ('PM2', 'Project Manager II'),
                                                    ('PM3', 'Project Manager III'), ('PPL', 'Project Planner'),
                                                    ('PCO', 'Project Coordinator'),
                                                    ('SUP', 'Project Management Supervisor')], default='PM1',
                                           max_length=3)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_num', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Enter project description', max_length=1000)),
                ('date_created', models.DateField(auto_now=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('prj_status', models.CharField(
                    choices=[('C', 'Complete'), ('I', 'In Progress'), ('P', 'Planning'), ('S', 'Scheduled')],
                    default='s', max_length=12)),
                ('prj_mgr',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.PrjMgr')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='prj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.Project'),
        ),
    ]
