# Generated by Django 2.1.7 on 2019-05-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resreq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prjmgr',
            old_name='title',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_status',
            field=models.CharField(
                choices=[('Complete', 'Complete'), ('B', 'Behind Schedule'), ('I', 'In Progress'), ('P', 'Planning'),
                         ('S', 'Scheduled')], default='S', max_length=12),
        ),
    ]
