# Generated by Django 2.1.7 on 2019-05-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0002_auto_20190506_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
