# Generated by Django 2.1.7 on 2019-05-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resreq', '0002_auto_20190430_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('D', 'Deployed')], default='A',
                                   max_length=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_status',
            field=models.TextField(
                choices=[('C', 'Complete'), ('B', 'Behind Schedule'), ('I', 'In Progress'), ('P', 'Planning'),
                         ('S', 'Scheduled')], default='S', max_length=12),
        ),
    ]
