# Generated by Django 2.1.7 on 2019-05-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0003_auto_20190506_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='str_pjr_mgr',
            field=models.TextField(default='', verbose_name=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.PrjMgr')),
        ),
        migrations.AddField(
            model_name='project',
            name='str_pjr_mgr',
            field=models.TextField(default='', verbose_name=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.PrjMgr')),
        ),
    ]
