# Generated by Django 2.1.7 on 2019-05-01 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resreq', '0003_auto_20190430_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('item_num', models.UUIDField(db_index=True, default=uuid.uuid4,
                                              help_text='Unique ID for this particular item across whole library')),
                ('notes', models.CharField(max_length=500, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('status',
                 models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('D', 'Deployed')], default='A',
                                  max_length=9)),
                ('description', models.CharField(
                    choices=[('BLDG', 'Building Materials'), ('LVRM', 'Living Room'), ('KITC', 'Kitchen'),
                             ('BDRM', 'Bedroom'), ('BATH', 'Bathroom'), ('CLTH', 'Clothing'), ('OUTD', 'Outdoor'),
                             ('PETS', 'Pet Supplies'), ('RECR', 'Recreational'), ('VEHI', 'Vehicle')], default='BLDG',
                    max_length=4)),
                ('sector', models.CharField(
                    choices=[('NW', 'North-West'), ('NC', 'North-Center'), ('NE', 'North-East'), ('CW', 'Central-West'),
                             ('CC', 'Central-Center'), ('CE', 'Central-East'), ('SW', 'South-West'),
                             ('SC', 'South-Center'), ('SE', 'South-East'), ('OS', 'Off site')], default='NW',
                    max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('borrower', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                               to=settings.AUTH_USER_MODEL)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrjMgr',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emp_num', models.IntegerField(blank=True, db_index=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='joined')),
                ('role', models.CharField(choices=[('PM1', 'Project Manager I'), ('PM2', 'Project Manager II'),
                                                   ('PM3', 'Project Manager III'), ('PPL', 'Project Planner'),
                                                   ('PCO', 'Project Coordinator'),
                                                   ('SUP', 'Project Management Supervisor')], default='PM1',
                                          max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical prj mgr',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('prj_num', models.IntegerField(blank=True, db_index=True)),
                ('summary', models.TextField(help_text='Enter project description', max_length=1000)),
                ('date_created', models.DateField(blank=True, editable=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('prj_status', models.TextField(
                    choices=[('Complete', 'Complete'), ('B', 'Behind Schedule'), ('I', 'In Progress'),
                             ('P', 'Planning'), ('S', 'Scheduled')], default='Scheduled', max_length=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('prj_mgr', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='resreq.PrjMgr')),
            ],
            options={
                'verbose_name': 'historical project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_status',
            field=models.TextField(
                choices=[('Complete', 'Complete'), ('B', 'Behind Schedule'), ('I', 'In Progress'), ('P', 'Planning'),
                         ('S', 'Scheduled')], default='Scheduled', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='prj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='resreq.Project'),
        ),
    ]
