# Generated by Django 2.1.7 on 2019-05-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0004_auto_20190507_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='str_pjr_mgr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='str_pjr_mgr',
        ),
    ]
