# Generated by Django 2.1.7 on 2019-05-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('resreq', '0004_auto_20190430_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='prj_status',
            field=models.TextField(
                choices=[('C', 'Complete'), ('B', 'Behind Schedule'), ('I', 'In Progress'), ('P', 'Planning'),
                         ('S', 'Scheduled')], default='Scheduled', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter project description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='resreq.PrjMgr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_status',
            field=models.TextField(
                choices=[('C', 'Complete'), ('B', 'Behind Schedule'), ('I', 'In Progress'), ('P', 'Planning'),
                         ('S', 'Scheduled')], default='Scheduled', max_length=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter project description', max_length=1000, null=True),
        ),
    ]
