# Generated by Django 2.1.7 on 2019-05-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0007_auto_20190507_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='resreq.Project'),
        ),
    ]
