# Generated by Django 2.1.7 on 2019-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resreq', '0007_auto_20190501_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='description',
            field=models.CharField(
                choices=[('Building Materials', 'Building Materials'), ('Living Room', 'Living Room'),
                         ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'),
                         ('Clothing', 'Clothing'), ('Outdoor', 'Outdoor'), ('Pet Supplies', 'Pet Supplies'),
                         ('Recreational', 'Recreational'), ('Vehicle', 'Vehicle')], default='BLDG', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(
                choices=[('Building Materials', 'Building Materials'), ('Living Room', 'Living Room'),
                         ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'),
                         ('Clothing', 'Clothing'), ('Outdoor', 'Outdoor'), ('Pet Supplies', 'Pet Supplies'),
                         ('Recreational', 'Recreational'), ('Vehicle', 'Vehicle')], default='BLDG', max_length=25),
        ),
    ]
