# Generated by Django 2.1.7 on 2019-05-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0008_auto_20190507_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='item',
            name='borrower',
        ),
    ]
