# Generated by Django 2.1.7 on 2019-05-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('resreq', '0008_auto_20190501_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='prj_status',
            field=models.TextField(choices=[('Behind Schedule', 'Behind Schedule'), ('Complete', 'Complete'),
                                            ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'),
                                            ('Planning', 'Planning')], default='Planning', max_length=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='resreq.PrjMgr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_status',
            field=models.TextField(choices=[('Behind Schedule', 'Behind Schedule'), ('Complete', 'Complete'),
                                            ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'),
                                            ('Planning', 'Planning')], default='Planning', max_length=12),
        ),
    ]
