# Generated by Django 2.1.7 on 2019-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0009_auto_20190501_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='description',
            field=models.TextField(choices=[('Building Materials', 'Building Materials'), ('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Clothing', 'Clothing'), ('Outdoor', 'Outdoor'), ('Pet Supplies', 'Pet Supplies'), ('Recreational', 'Recreational'), ('Vehicle', 'Vehicle')], default='Outdoor', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='status',
            field=models.TextField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Deployed', 'Deployed')], default='Available', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(choices=[('Building Materials', 'Building Materials'), ('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Clothing', 'Clothing'), ('Outdoor', 'Outdoor'), ('Pet Supplies', 'Pet Supplies'), ('Recreational', 'Recreational'), ('Vehicle', 'Vehicle')], default='Outdoor', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.TextField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Deployed', 'Deployed')], default='Available', max_length=25),
        ),
    ]
