# Generated by Django 2.1.7 on 2019-05-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0010_auto_20190501_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='sector',
            field=models.CharField(choices=[('NW', 'North-West'), ('North-Center', 'North-Center'), ('North-East', 'North-East'), ('Central-West', 'Central-West'), ('Central-Center', 'Central-Center'), ('Central-East', 'Central-East'), ('South-West', 'South-West'), ('South-Center', 'South-Center'), ('South-East', 'South-East'), ('Off Site', 'Off site')], default='North-West', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='prj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resreq.Project'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sector',
            field=models.CharField(choices=[('NW', 'North-West'), ('North-Center', 'North-Center'), ('North-East', 'North-East'), ('Central-West', 'Central-West'), ('Central-Center', 'Central-Center'), ('Central-East', 'Central-East'), ('South-West', 'South-West'), ('South-Center', 'South-Center'), ('South-East', 'South-East'), ('Off Site', 'Off site')], default='North-West', max_length=25),
        ),
    ]
