# Generated by Django 2.1.7 on 2019-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resreq', '0011_auto_20190501_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='sector',
            field=models.CharField(choices=[('North-West', 'NW'), ('North-Center', 'North-Center'), ('North-East', 'North-East'), ('Central-West', 'Central-West'), ('Central-Center', 'Central-Center'), ('Central-East', 'Central-East'), ('South-West', 'South-West'), ('South-Center', 'South-Center'), ('South-East', 'South-East'), ('Off Site', 'Off site')], default='North-West', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='sector',
            field=models.CharField(choices=[('North-West', 'NW'), ('North-Center', 'North-Center'), ('North-East', 'North-East'), ('Central-West', 'Central-West'), ('Central-Center', 'Central-Center'), ('Central-East', 'Central-East'), ('South-West', 'South-West'), ('South-Center', 'South-Center'), ('South-East', 'South-East'), ('Off Site', 'Off site')], default='North-West', max_length=25),
        ),
    ]
