# Generated by Django 2.1.7 on 2019-04-15 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190413_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_num', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('D', 'Deployed')], default='A', max_length=1)),
                ('description', models.CharField(choices=[('BLD', 'Building Materials'), ('LVR', 'Living Room'), ('KIT', 'Kitchen'), ('BDR', 'Bedroom'), ('BAT', 'Bathroom'), ('CLT', 'Clothing'), ('OUT', 'Outdoor'), ('PET', 'Pet Supplies'), ('REC', 'Recreational'), ('VEH', 'Vehicle')], default='BLD', max_length=3)),
                ('sector', models.CharField(choices=[('NW', 'North-West'), ('NC', 'North-Center'), ('NE', 'North-East'), ('CW', 'Central-West'), ('CC', 'Central-Center'), ('CE', 'Central-East'), ('SW', 'South-West'), ('SC', 'South-Center'), ('SE', 'South-East')], default='NW', max_length=2)),
                ('notes', models.CharField(default='Notes', max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrjMgr',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emp_num', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='joined')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_num', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('prj_mgr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PrjMgr')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='item',
            name='prj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Project'),
        ),
    ]
