# Generated by Django 2.1.7 on 2019-04-15 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190415_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_num',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular item across whole library', primary_key=True, serialize=False),
        ),
    ]
