# Generated by Django 2.1.7 on 2019-04-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190415_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(help_text='Enter project description', max_length=1000),
        ),
    ]
