# Generated by Django 2.1.7 on 2019-04-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190423_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prj_mgr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PrjMgr'),
        ),
    ]
