# Generated by Django 2.1.7 on 2019-04-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_prj_mgr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='prj_mgr',
        ),
    ]
